# Generated by Django 4.0 on 2021-12-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField(max_length=12)),
                ('ename', models.CharField(max_length=20)),
                ('elast', models.CharField(max_length=20)),
                ('eemail', models.EmailField(max_length=254)),
                ('cname', models.CharField(max_length=20)),
                ('econtact', models.CharField(max_length=10)),
            ],
        ),
    ]
